export const cartType='CART_TYPE'
export const selectType='SELECT_TYPE'
export const countType='COUNT_TYPE'
export const goodsSelectType='GOODS_SELECT_TYPE'
export const changeSelectAllType='CHANGESELECT_ALL_TYPE'
export const delType='DELTYPE_TYPE'
export const collectType='COLLECT_TYPE'
